<x-layouts.admin title="Layanan">
<div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="font-display text-2xl font-bold sm:text-3xl">Layanan</h1><p class="mt-1 text-sm text-muted-foreground">Kelola katalog layanan barbershop.</p></div><button data-dialog-open="add-service" class="btn-gold btn-gold-hover inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-semibold"><x-icon name="plus" class="h-4 w-4"/>Tambah Layanan</button></div>
<div class="card-premium mt-6 overflow-x-auto rounded-xl"><table class="w-full text-sm"><thead class="bg-background/40 text-xs uppercase text-muted-foreground"><tr><th class="px-4 py-3 text-left">Nama</th><th class="px-4 py-3 text-left">Deskripsi</th><th class="px-4 py-3 text-left">Durasi</th><th class="px-4 py-3 text-left">Harga</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody>
@foreach($services as $service)<tr class="border-t border-border"><td class="px-4 py-3 font-medium">{{ $service->name }}</td><td class="max-w-xs px-4 py-3 text-muted-foreground">{{ $service->description }}</td><td class="px-4 py-3">{{ $service->duration }} mnt</td><td class="px-4 py-3 font-semibold gold-text">Rp{{ number_format($service->price,0,',','.') }}</td><td class="px-4 py-3"><span class="rounded-full border px-2 py-0.5 text-xs {{ $service->status==='aktif' ? 'border-success/40 bg-success/10 text-success' : 'border-border bg-muted text-muted-foreground' }}">{{ $service->status }}</span></td><td class="px-4 py-3"><div class="flex justify-end gap-1"><button data-dialog-open="edit-service-{{ $service->id }}" class="rounded p-1.5 text-primary hover:bg-primary/10"><x-icon name="pencil" class="h-4 w-4"/></button><form method="POST" action="{{ route('admin.services.destroy',$service) }}" data-confirm="Hapus layanan {{ $service->name }}?">@csrf @method('DELETE')<button class="rounded p-1.5 text-destructive hover:bg-destructive/10"><x-icon name="trash" class="h-4 w-4"/></button></form></div></td></tr>@endforeach
</tbody></table></div>

@foreach($services as $service)
<dialog id="edit-service-{{ $service->id }}" class="m-auto w-[min(92vw,520px)] rounded-xl border border-border bg-popover p-0 text-foreground"><form method="POST" action="{{ route('admin.services.update',$service) }}" class="p-6">@csrf @method('PUT')<div class="flex justify-between"><h2 class="font-display text-xl font-bold">Edit Layanan</h2><button type="button" data-dialog-close><x-icon name="x"/></button></div><div class="mt-5 space-y-4"><x-field label="Nama Layanan"><input name="name" value="{{ $service->name }}" class="input-control" required></x-field><x-field label="Deskripsi"><textarea name="description" rows="2" class="input-control">{{ $service->description }}</textarea></x-field><div class="grid grid-cols-2 gap-3"><x-field label="Durasi (menit)"><input type="number" min="5" name="duration" value="{{ $service->duration }}" class="input-control"></x-field><x-field label="Harga (Rp)"><input type="number" min="0" name="price" value="{{ $service->price }}" class="input-control"></x-field></div><x-field label="Status"><select name="status" class="input-control"><option value="aktif" @selected($service->status==='aktif')>Aktif</option><option value="nonaktif" @selected($service->status==='nonaktif')>Nonaktif</option></select></x-field></div><div class="mt-6 flex justify-end"><button class="btn-gold rounded-md px-4 py-2 text-sm">Simpan</button></div></form></dialog>
@endforeach

<dialog id="add-service" class="m-auto w-[min(92vw,520px)] rounded-xl border border-border bg-popover p-0 text-foreground"><form method="POST" action="{{ route('admin.services.store') }}" class="p-6">@csrf<div class="flex justify-between"><h2 class="font-display text-xl font-bold">Tambah Layanan</h2><button type="button" data-dialog-close><x-icon name="x"/></button></div><div class="mt-5 space-y-4"><x-field label="Nama Layanan"><input name="name" class="input-control" required></x-field><x-field label="Deskripsi"><textarea name="description" rows="2" class="input-control"></textarea></x-field><div class="grid grid-cols-2 gap-3"><x-field label="Durasi (menit)"><input type="number" min="5" name="duration" value="45" class="input-control"></x-field><x-field label="Harga (Rp)"><input type="number" min="0" name="price" value="35000" class="input-control"></x-field></div><x-field label="Status"><select name="status" class="input-control"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></x-field></div><div class="mt-6 flex justify-end"><button class="btn-gold rounded-md px-4 py-2 text-sm">Simpan</button></div></form></dialog>
</x-layouts.admin>
