@props(['title' => 'Admin Panel'])
<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title }} — XYZ Admin</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body><div class="flex min-h-screen w-full">
<aside id="admin-sidebar" class="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-sidebar-border bg-sidebar md:relative md:flex md:flex-col">
<div class="flex h-16 items-center justify-between border-b border-sidebar-border px-5"><a href="{{ route('home') }}" class="flex items-center gap-2"><div class="grid h-8 w-8 place-items-center rounded-lg gold-gradient"><x-icon name="scissors" class="h-4 w-4 text-background"/></div><div class="font-display font-bold gold-text">XYZ Admin</div></a><button class="text-muted-foreground md:hidden" data-menu-toggle="admin-sidebar"><x-icon name="x"/></button></div>
@php($items=[['admin.dashboard','dashboard','Dashboard'],['admin.queues','list','Daftar Antrean'],['admin.services','scissors','Layanan'],['admin.capacities','users','Kapasitas Barber'],['admin.reports','chart','Laporan']])
<nav class="flex-1 space-y-1 p-3">@foreach($items as [$routeName,$icon,$label])<a href="{{ route($routeName) }}" class="flex items-center gap-3 rounded-md px-3 py-2 text-sm transition {{ request()->routeIs($routeName) ? 'border border-primary/40 bg-primary/15 text-primary' : 'text-muted-foreground hover:bg-sidebar-accent hover:text-foreground' }}"><x-icon :name="$icon" class="h-4 w-4"/>{{ $label }}</a>@endforeach</nav>
<form method="POST" action="{{ route('logout') }}" class="m-3">@csrf<button class="flex w-full items-center gap-3 rounded-md border border-border px-3 py-2 text-sm text-muted-foreground hover:border-destructive/50 hover:text-destructive"><x-icon name="logout" class="h-4 w-4"/>Keluar</button></form>
</aside>
<div class="flex min-w-0 flex-1 flex-col"><header class="flex h-16 items-center justify-between border-b border-border bg-popover px-4 md:px-6"><button class="text-foreground md:hidden" data-menu-toggle="admin-sidebar"><x-icon name="menu"/></button><div class="text-sm text-muted-foreground">Admin Panel</div><div class="text-sm">Hai, <span class="font-semibold text-primary">{{ auth()->user()->name }}</span></div></header>
@if(session('success') || session('error') || $errors->any())<div class="fixed right-4 top-20 z-50 max-w-sm space-y-2">@if(session('success'))<div class="toast rounded-lg border border-success/40 bg-popover px-4 py-3 text-sm text-success shadow-xl">{{ session('success') }}</div>@endif @if(session('error'))<div class="toast rounded-lg border border-destructive/40 bg-popover px-4 py-3 text-sm text-destructive shadow-xl">{{ session('error') }}</div>@endif @if($errors->any())<div class="toast rounded-lg border border-destructive/40 bg-popover px-4 py-3 text-sm text-destructive shadow-xl">{{ $errors->first() }}</div>@endif</div>@endif
<main class="flex-1 p-4 md:p-8">{{ $slot }}</main></div></div></body></html>
